-- phpMyAdmin SQL Dump
-- version 5.2.0
-- https://www.phpmyadmin.net/
--
-- Host: localhost:8889
-- Generation Time: May 11, 2023 at 06:00 PM
-- Server version: 5.7.39
-- PHP Version: 8.2.0

SET SQL_MODE = "NO_AUTO_VALUE_ON_ZERO";
START TRANSACTION;
SET time_zone = "+00:00";


/*!40101 SET @OLD_CHARACTER_SET_CLIENT=@@CHARACTER_SET_CLIENT */;
/*!40101 SET @OLD_CHARACTER_SET_RESULTS=@@CHARACTER_SET_RESULTS */;
/*!40101 SET @OLD_COLLATION_CONNECTION=@@COLLATION_CONNECTION */;
/*!40101 SET NAMES utf8mb4 */;

--
-- Database: `bookhive`
--

-- --------------------------------------------------------

--
-- Table structure for table `Books`
--

CREATE TABLE `Books` (
  `BookID` int(11) NOT NULL,
  `Title` varchar(100) NOT NULL,
  `AuthorID` int(11) NOT NULL,
  `PublisherID` int(11) NOT NULL,
  `CategoryID` int(11) NOT NULL,
  `PublicationDate` date NOT NULL,
  `Language` varchar(50) NOT NULL,
  `Pages` int(11) NOT NULL,
  `Price` decimal(10,2) NOT NULL,
  `Quantity` int(11) NOT NULL,
  `Description` text NOT NULL,
  `Genre` text NOT NULL,
  `ImageURL` varchar(255) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

--
-- Dumping data for table `Books`
--

INSERT INTO `Books` (`BookID`, `Title`, `AuthorID`, `PublisherID`, `CategoryID`, `PublicationDate`, `Language`, `Pages`, `Price`, `Quantity`, `Description`, `Genre`, `ImageURL`) VALUES
(1, 'In the Lives of Puppets', 1, 1, 1, '2023-04-25', 'English', 420, '14.99', 10, 'In a strange little home built into the branches of a grove of trees, live three robots--fatherly inventor android Giovanni Lawson, a pleasantly sadistic nurse machine, and a small vacuum desperate for love and attention. Victor Lawson, a human, lives there too. They\'re a family, hidden and safe.\r\n\r\nThe day Vic salvages and repairs an unfamiliar android labelled \"HAP,\" he learns of a shared dark past between Hap and Gio-a past spent hunting humans.\r\n\r\nWhen Hap unwittingly alerts robots from Gio\'s former life to their whereabouts, the family is no longer hidden and safe. Gio is captured and taken back to his old laboratory in the City of Electric Dreams. So together, the rest of Vic\'s assembled family must journey across an unforgiving and otherworldly country to rescue Gio from decommission, or worse, reprogramming.\r\n\r\nAlong the way to save Gio, amid conflicted feelings of betrayal and affection for Hap, Vic must decide for himself: Can he accept love with strings attached?', 'Fiction', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1653059893i/60784549.jpg'),
(2, 'Atlanta', 2, 2, 1, '2023-04-11', 'English', 304, '17.99', 15, 'From the beloved, bestselling author of Elektra and Ariadne , a reimagining of the myth of Atalanta, a fierce huntress raised by bears and the only woman in the world’s most famous band of heroes, the Argonauts\r\n\r\nPrincess, Warrior, Lover, Hero\r\n\r\nWhen Princess Atalanta is born, a daughter rather than the son her parents hoped for, she is left on a mountainside to die. But even then, she is a survivor. Raised by a mother bear under the protective eye of the goddess Artemis, Atalanta grows up wild and free, with just one condition: if she marries, Artemis warns, it will be her undoing.\r\n\r\nAlthough she loves her beautiful forest home, Atalanta yearns for adventure. When Artemis offers her the chance to fight in her name alongside the Argonauts, the fiercest band of warriors the world has ever seen, Atalanta seizes it. The Argonauts\' quest for the Golden Fleece is filled with impossible challenges, but Atalanta proves herself equal to the men she fights alongside. As she is swept into a passionate affair, in defiance of Artemis\'s warning, she begins to question the goddess\'s true intentions. Can Atalanta carve out her own legendary place in a world of men, while staying true to her heart?\r\n\r\nFull of joy, passion, and adventure, Atalanta is the story of a woman who refuses to be contained. Jennifer Saint places Atalanta in the pantheon of the greatest heroes in Greek mythology, where she belongs.', 'Fiction', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1675082381i/61884838.jpg'),
(3, 'The House Is on Fire', 3, 3, 1, '2023-04-04', 'English', 384, '14.99', 13, 'The author of Florence Adler Swims Forever returns with a masterful work of historical fiction about an incendiary tragedy that shocked a young nation and tore apart a community in a single night—told from the perspectives of four people whose actions during the inferno changed the course of history.\r\n\r\nRichmond, Virginia 1811. It’s the height of the winter social season. The General Assembly is in session, and many of Virginia’s gentleman planters, along with their wives and children, have made the long and arduous journey to the capital in hopes of whiling away the darkest days of the year. At the city’s only theater, the Charleston-based Placide & Green Company puts on two plays a night to meet the demand of a populace that’s done looking for enlightenment in a church.\r\n\r\nOn the night after Christmas, the theater is packed with more than six hundred holiday revelers. In the third-floor boxes, sits newly widowed Sally Henry Campbell, who is glad for any opportunity to relive the happy times she shared with her husband. One floor away, in the colored gallery, Cecily Patterson doesn’t give a whit about the play but is grateful for a four-hour reprieve from a life that has recently gone from bad to worse. Backstage, young stagehand Jack Gibson hopes that, if he can impress the theater’s managers, he’ll be offered a permanent job with the company. And on the other side of town, blacksmith Gilbert Hunt dreams of one day being able to bring his wife to the theater, but he’ll have to buy her freedom first.\r\n\r\nWhen the theater goes up in flames in the middle of the performance, Sally, Cecily, Jack, and Gilbert make a series of split-second decisions that will not only affect their own lives but those of countless others. And in the days following the fire, as news of the disaster spreads across the United States, the paths of these four people will become forever intertwined.\r\n\r\nBased on the true story of Richmond’s theater fire, The House Is on Fire offers proof that sometimes, in the midst of great tragedy, we are offered our most precious—and fleeting—chances at redemption.', 'Fiction', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1678326118i/61273814.jpg'),
(4, 'The Trackers', 4, 4, 1, '2023-04-11', 'English', 336, '15.99', 14, 'From the New York Times bestselling author of Cold Mountain and Varina, a stunning new novel that paints a vivid portrait of life in the Great Depression\r\n\r\nHurtling past the downtrodden communities of Depression-era America, painter Val Welch travels westward to the rural town of Dawes, Wyoming. Through a stroke of luck, he\'s landed a New Deal assignment to create a mural representing the region for their new Post Office.\r\n\r\nA wealthy art lover named John Long and his wife Eve have agreed to host Val at their sprawling ranch. Rumors and intrigue surround the couple: Eve left behind an itinerant life riding the rails and singing in a western swing band. Long holds shady political aspirations, but was once a WWI sniper--and his right hand is a mysterious elder cowboy, a vestige of the violent old west. Val quickly finds himself entranced by their lives.\r\n\r\nOne day, Eve flees home with a valuable painting in tow, and Long recruits Val to hit the road with a mission of tracking her down. Journeying from ramshackle Hoovervilles to San Francisco nightclubs to the swamps of Florida, Val\'s search for Eve narrows, and he soon turns up secrets that could spark formidable changes for all of them.\r\n\r\nIn The Trackers, singular American writer Charles Frazier conjures up the lives of everyday people during an extraordinary period of history that bears uncanny resemblance to our own. With the keen perceptions of humanity and transcendent storytelling that have made him beloved for decades, Frazier has created a powerful and timeless new classic.', 'Fiction', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1675640849i/61609871.jpg'),
(5, 'The Diary of a Young Girl', 5, 1, 2, '1947-01-01', 'English', 283, '19.99', 11, 'Discovered in the attic in which she spent the last years of her life, Anne Frank’s remarkable diary has become a world classic—a powerful reminder of the horrors of war and an eloquent testament to the human spirit.\r\n\r\nIn 1942, with the Nazis occupying Holland, a thirteen-year-old Jewish girl and her family fled their home in Amsterdam and went into hiding. For the next two years, until their whereabouts were betrayed to the Gestapo, the Franks and another family lived cloistered in the “Secret Annexe” of an old office building. Cut off from the outside world, they faced hunger, boredom, the constant cruelties of living in confined quarters, and the ever-present threat of discovery and death. In her diary Anne Frank recorded vivid impressions of her experiences during this period. By turns thoughtful, moving, and surprisingly humorous, her account offers a fascinating commentary on human courage and frailty and a compelling self-portrait of a sensitive and spirited young woman whose promise was tragically cut short.\r\n--back cover', 'Non-fiction', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1560816565i/48855.jpg'),
(6, 'Sapiens: A Brief History of Humankind', 6, 2, 2, '2011-01-01', 'english', 512, '25.99', 20, '100,000 years ago, at least six human species inhabited the earth. Today there is just one. Us. Homo sapiens.\r\n\r\nHow did our species succeed in the battle for dominance? Why did our foraging ancestors come together to create cities and kingdoms? How did we come to believe in gods, nations and human rights; to trust money, books and laws; and to be enslaved by bureaucracy, timetables and consumerism? And what will our world be like in the millennia to come?\r\n\r\nIn Sapiens, Dr Yuval Noah Harari spans the whole of human history, from the very first humans to walk the earth to the radical – and sometimes devastating – breakthroughs of the Cognitive, Agricultural and Scientific Revolutions. Drawing on insights from biology, anthropology, paleontology and economics, he explores how the currents of history have shaped our human societies, the animals and plants around us, and even our personalities. Have we become happier as history has unfolded? Can we ever free our behaviour from the heritage of our ancestors? And what, if anything, can we do to influence the course of the centuries to come?\r\n\r\nBold, wide-ranging and provocative, Sapiens challenges everything we thought we knew about being human: our thoughts, our actions, our power ... and our future.', 'Non-fiction', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1595674533i/23692271.jpg'),
(7, 'Educated', 7, 3, 2, '2018-02-20', 'english', 352, '17.99', 14, 'Tara Westover was 17 the first time she set foot in a classroom. Born to survivalists in the mountains of Idaho, she prepared for the end of the world by stockpiling home-canned peaches and sleeping with her \"head-for-the-hills bag\". In the summer she stewed herbs for her mother, a midwife and healer, and in the winter she salvaged in her father\'s junkyard.\r\n\r\nHer father forbade hospitals, so Tara never saw a doctor or nurse. Gashes and concussions, even burns from explosions, were all treated at home with herbalism. The family was so isolated from mainstream society that there was no one to ensure the children received an education and no one to intervene when one of Tara\'s older brothers became violent.\r\n\r\nThen, lacking any formal education, Tara began to educate herself. She taught herself enough mathematics and grammar to be admitted to Brigham Young University, where she studied history, learning for the first time about important world events like the Holocaust and the civil rights movement. Her quest for knowledge transformed her, taking her over oceans and across continents, to Harvard and to Cambridge. Only then would she wonder if she\'d traveled too far, if there was still a way home.\r\n\r\nEducated is an account of the struggle for self-invention. It is a tale of fierce family loyalty and of the grief that comes with severing the closest of ties. With the acute insight that distinguishes all great writers, Westover has crafted a universal coming-of-age story that gets to the heart of what an education is and what it offers: the perspective to see one\'s life through new eyes and the will to change it.', 'Non-fiction', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1506026635i/35133922.jpg'),
(8, 'Quiet: The Power of Introverts in a World That Can\'t Stop Talking', 8, 4, 2, '2012-01-24', 'english', 333, '17.99', 17, 'At least one-third of the people we know are introverts. They are the ones who prefer listening to speaking; who innovate and create but dislike self-promotion; who favor working on their own over working in teams. It is to introverts—Rosa Parks, Chopin, Dr. Seuss, Steve Wozniak—that we owe many of the great contributions to society. \r\n\r\nIn Quiet, Susan Cain argues that we dramatically undervalue introverts and shows how much we lose in doing so. She charts the rise of the Extrovert Ideal throughout the twentieth century and explores how deeply it has come to permeate our culture. She also introduces us to successful introverts—from a witty, high-octane public speaker who recharges in solitude after his talks, to a record-breaking salesman who quietly taps into the power of questions. Passionately argued, superbly researched, and filled with indelible stories of real people, Quiet has the power to permanently change how we see introverts and, equally important, how they see themselves.\r\n\r\nNow with Extra Libris material, including a reader’s guide and bonus content.', 'Non-fiction', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1328562861i/8520610.jpg'),
(9, 'A Living Remedy: A Memoir', 9, 1, 3, '2023-04-04', 'English', 256, '15.99', 11, 'From the bestselling author of ALL YOU CAN EVER KNOW comes a searing memoir of family, class and grief—a daughter’s search to understand the lives her adoptive parents led, the life she forged as an adult, and the lives she’s lost. In this country, unless you attain extraordinary wealth, you will likely be unable to help your loved ones in all the ways you’d hoped. You will learn to live with the specific, hollow guilt of those who leave hardship behind, yet are unable to bring anyone else with them.  Nicole Chung couldn’t hightail it out of her overwhelmingly white Oregon hometown fast enough. As a scholarship student at a private university on the East Coast, no longer the only Korean she knew, she found community and a path to the life she\'d long wanted. But the middle class world she begins to raise a family in – where there are big homes, college funds, nice vacations – looks very different from the middle class world she thought she grew up in, where paychecks have to stretch to the end of the week, health insurance is often lacking, and there are no safety nets. When her father dies at only sixty-seven, killed by diabetes and kidney disease, Nicole feels deep grief as well as rage, knowing that years of precarity and lack of access to healthcare contributed to his early death. And then the unthinkable happens – less than a year later, her beloved mother is diagnosed with cancer, and the physical distance between them becomes insurmountable as COVID-19 descends upon the world.  Exploring the enduring strength of family bonds in the face of hardship and tragedy,  A Living Remedy  examines what it takes to reconcile the distance between one life, one home, and another – and sheds needed light on some of the most persistent and grievous inequalities in American society. ', 'Biography', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1675641094i/62050250.jpg'),
(10, 'This Isn\'t Going to End Well: The True Story of a Man I Thought I Knew', 10, 2, 3, '2023-04-11', 'english', 272, '13.99', 12, '“A memoir wrapped in an elegy… [that] maps a strangely stunning life… [Wallace] imbues this chronicle with tremendous compassion — for William, for everyone.  This Isn’t Going to End Well  gives off the particular radiance of a life lived hard, whatever as such, a brand of American bildungsroman. There’s deep satisfaction to its arc, despite its inherent sadness — a wondrous glimpse of the melding, in human doings, of fate, character and serendipity.”― Washington Post\r\n\r\n﻿“Daniel Wallace has, once again, shown himself to be an exquisite storyteller.  Like bourbon, this book goes down hot and strong but finishes with a salving sweetness which can only be called a blessing.  A love story and a ghost story a once,  This Isn’t Going to End Well  straddles the line between present and past, truth and beauty.”―Tayari Jones, author of An American Marriage\r\n\r\nA profoundly moving, large-hearted, genre-bending memoir from the bestselling author of Big Fish .\r\n\r\nIf we’re lucky, we all encounter at least one person whose life elevates and inspires our own. For Daniel Wallace, that was his longtime friend and brother-in-law, William Nealy. Seemingly perfect, impossibly cool, William was James Dean, Clint Eastwood, and MacGyver all rolled into an acclaimed outdoorsman, a famous cartoonist, an accomplished author, a master of all he undertook. William was the ideal that Daniel sought to emulate, and the person who gave him the courage to become a writer.\r\n\r\nBut when William took his own life at age forty eight, Daniel’s heartbreak led him to commit a grievous act of his own, a betrayal that took him down a path into the tortured recesses of William’s past. Eventually a new picture emerged of a man with too many secrets and too much shame to bear.\r\n\r\nWith his first memoir, acclaimed writer Daniel Wallace delivers a stunning book that is as innovative and emotionally resonant as his novels. Part love story, part true crime, part a desperate search for the self, This Isn’t Going to End Well tells an intimate and moving story of what happens when we realize our heroes are human.', 'Biography', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1674579831i/60831912.jpg'),
(11, 'The Windsors at War: The King, His Brother, and a Family Divided', 11, 3, 3, '2023-04-18', 'english', 432, '18.99', 15, 'The next volume in Alexander Larman\'s biographical chronicle of the Windsor family, as they go to war with Adolf Hitler―and each other.\r\n\r\n\r\nAt the beginning of 1937, the British monarchy was in a state of turmoil. The previous king, Edward VIII, had abdicated the throne, leaving his unprepared and terrified brother Bertie to become George VI, surrounded by a gaggle of courtiers and politicians who barely thought him up to the job. Meanwhile, as the now-Duke of Windsor awaited the decree that would allow him to marry his mistress Wallis Simpson, he took an increased interest in the expansionist plans of Adolf Hitler. He may even have gone so far as to betray his country in the process. And as double agents and Nazi spies thronged the corridors of Buckingham Palace, the only man the King could trust was his Prime Minister, Winston Churchill. But they faced a formidable, even unbeatable, adversary: his own brother.\r\n\r\nThe Windsors at War tells the never-before-told story of World War Two in Britain and America with a fresh focus on the royal family, their conflicted relationships, and the events that rocked the international press. How did this squabbling, dysfunctional family manage to put their differences aside and unite to help win the greatest conflict of their lifetimes? Alexander Larman, author of The Crown in Crisis, now chronicles the Windsor family at war with Germany―and each other.', 'Biography', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1660053633i/60784528.jpg'),
(12, 'Koresh: The True Story of David Koresh and the Tragedy at Waco', 12, 4, 3, '2023-04-11', 'english', 464, '16.99', 18, 'The first comprehensive account of David Koresh\'s life, his road to Waco, and the rise of government mistrust in America, from a master of narrative nonfiction\r\n\r\nNo other event in the last fifty years is shrouded in myth like the 1993 siege of the Branch Davidians in Waco, Texas. Today, we remember this moment for the 76 people, including 20 children, who died in the fire; for its inspiration of the Oklahoma City bombing; and for the wave of anti-government militarism that followed. What we understand far less is what motivated the Davidians\' enigmatic leader, David Koresh.\r\n\r\nDrawing on first-time, exclusive interviews with Koresh\'s family and survivors of the siege, bestselling author Stephan Talty paints a psychological portrait of this infamous icon of the 1990s. Born Vernon Howell into the hyper-masculine world of central Texas in the 1960s, Koresh experienced a childhood riven with abuse and isolation. He found a new version of himself in the halls of his local church, and love in the fundamentalist sect of the Branch Davidians. Later, with a new name and professed prophetic powers, Koresh ushered in a new era for the Davidians that prized his own sexual conquest as much as his followers\' faith. As one survivor has said, \"What better way for a worthless child to feel worth than to become God?\"\r\n\r\nIn his signature immersive storytelling, Talty reveals how Koresh\'s fixation on holy war, which would deliver the Davidians to their reward and confirm himself as Christ, collided with his paranoid obsession with firearms to destructive effect. Their deadly, 51-day standoff with the embattled FBI and ATF, he shows, embodied an anti-government ethic that continues to resonate today.\r\n\r\nNow, thirty years after that unforgettable moment, Koresh presents the tragedy at Waco--and the government mistrust it inspired--in its fullest context yet.', 'Biography', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1675644037i/61605678.jpg'),
(13, 'Nic Blake and the Remarkables: The Manifestor Prophecy', 13, 1, 4, '2023-04-04', 'English', 304, '12.99', 11, 'Internationally bestselling superstar author Angie Thomas makes her middle grade debut with the launch of an inventive, hilarious, and suspenseful new contemporary fantasy trilogy inspired by African American history and folklore.\r\n\r\nIt’s not easy being a Remarkable in the Unremarkable world. Some things are cool—like getting a pet hellhound for your twelfth birthday. Others, not so much—like not being trusted to learn magic because you might use it to take revenge on an annoying neighbor.\r\n\r\nAll Nic Blake wants is to be a powerful Manifestor like her dad. But before she has a chance to convince him to teach her the gift, a series of shocking revelations and terrifying events launch Nic and two friends on a hunt for a powerful magic tool she’s never heard of...to save her father from imprisonment for a crime she refuses to believe he committed.', 'Children', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1661872909i/62194599.jpg'),
(14, 'Pebble and Wren', 14, 2, 4, '2023-04-11', 'english', 240, '10.99', 13, 'A little girl and her live-in monster learn about what makes them different—and what unites them. This graphic novel is a silly, sweet, and sometimes gross tribute to friendship, and to the wacky world we live in.\r\n\r\nBased on his webcomic of the same name, Pebble and Wren follows human girl Wren and her live-in monster, Pebble, as she teaches them all about how the human world works—from why the moon changes shape to why we don\'t eat candy wrappers—while trying to unlock special abilities without which Pebble will have to return to the monster forest.\r\n\r\nA silly, sweet, and sometimes gross tribute to friendship for fans of Calvin & Hobbes and Catwad.', 'Children', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1675642113i/61605676.jpg'),
(15, 'School Trip', 15, 3, 4, '2023-04-04', 'english', 247, '12.99', 14, 'New York Times bestselling author Jerry Craft is back with the newest adventures of Jordan, Drew, Liam, and all the characters that fans first met in New Kid, winner of the Newbery Award and the Coretta Scott King Author Award! In this full-color contemporary graphic novel, the gang from Riverdale Academy Day is heading to Paris, for an international education like you\'ve never seen before ...\r\n\r\nJordan, Drew, Liam, Maury, and their friends from Riverdale Academy Day School are heading out on a school trip to Paris. As an aspiring artist himself, Jordan can\'t wait to see all the amazing art in the famous City of Lights.\r\n\r\nBut when their trusted faculty guides are replaced at the last minute, the school trip takes an unexpected--and hilarious--turn. Especially when trying to find their way around a foreign city ends up being almost as tricky as navigating the same friendships, fears, and differences that they struggle with at home.\r\n\r\nWill Jordan and his friends embrace being exposed to a new language, unfamiliar food, and a different culture? Or will they all end up feeling like the \"new kid\"?\r\n\r\nDon\'t miss the two hilarious and powerful companion novels by Jerry Craft, New Kid and Class Act!', 'Children', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1658861587i/61419629.jpg'),
(16, 'Creatures of the In Between', 16, 4, 4, '2023-04-11', 'english', 416, '10.99', 14, 'Princess Mononoke meets How to Train Your Dragon in this magical middle-grade adventure from Cindy Lin, author of The Twelve, featuring a blend of East and Southeast Asian folklore and mythical creatures, and starring a boy with a hero\'s destiny.\r\n\r\nPrince Jin is running out of time. He must find a monster companion before his thirteenth birthday or lose the throne completely, and that means travelling to the only place where monsters still live: the legendary, dangerous Whisper Island. But untold perils await Jin there. The magical creatures he seeks are not so easily swayed, and an even greater threat looms on the horizon--one that could threaten everything Jin hopes to achieve.', 'Children', 'https://images-na.ssl-images-amazon.com/images/S/compressed.photo.goodreads.com/books/1675640446i/61604785.jpg');

--
-- Indexes for dumped tables
--

--
-- Indexes for table `Books`
--
ALTER TABLE `Books`
  ADD PRIMARY KEY (`BookID`),
  ADD KEY `AuthorID` (`AuthorID`),
  ADD KEY `PublisherID` (`PublisherID`),
  ADD KEY `CategoryID` (`CategoryID`);

--
-- Constraints for dumped tables
--

--
-- Constraints for table `Books`
--
ALTER TABLE `Books`
  ADD CONSTRAINT `books_ibfk_1` FOREIGN KEY (`AuthorID`) REFERENCES `Authors` (`AuthorID`),
  ADD CONSTRAINT `books_ibfk_2` FOREIGN KEY (`PublisherID`) REFERENCES `Publishers` (`PublisherID`),
  ADD CONSTRAINT `books_ibfk_3` FOREIGN KEY (`CategoryID`) REFERENCES `Categories` (`CategoryID`);
COMMIT;

/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
